### ISSUE TITLE
Perhaps a deeper dive into problems

### ISSUE THREAD

**Issue by BrickerBrickerOneNine** [atoddj/squirtle-issues#11]
Lets take a look at Medvizer > User/Login.

its two categories and then technically two resolutions for the first, and there will be more as we populate more data. I think that the expansion is good, but the difference in the bullets currently of "Account may be locked out" and "Forgotten password" should also be clickable. I don't want to be crazy and theres a million clicks to a resolution, but i do want to be able to be granular as we progress and add more content. So something to think about

**Comment by atoddj** [comment]
does this relate to #3 ?

**Comment by BrickerBrickerOneNine** [comment]
Not necessarily, the functionality of #3 was just that, this is the ability to have multiple resolutions within each resolution. We can go over with a remote session later if needed

**Comment by BrickerBrickerOneNine** [comment]
No longer needed.
