### ISSUE TITLE
Change "MedVizer" to "Virtual Health Now"

### ISSUE THREAD

**Issue by BrickerBrickerOneNine** [atoddj/squirtle-issues#14]

**Comment by BrickerBrickerOneNine** [comment]
No better category than bug, however MedVizer should no longer be used.

**Comment by BrickerBrickerOneNine** [comment]
Put in ( ) CHS Only. put an * in small letters perhaps that says "LIfepoint and CMC do not use Virtual health now".
All other documentation will be the same

**Comment by atoddj** [comment]
Updated the text and urls. Working on content in a separate ticket
