### ISSUE TITLE
Footer should say "Powered by" and then the monarch logo

### ISSUE THREAD

**Issue by atoddj** [atoddj/squirtle-issues#5]

**Comment by atoddj** [comment]
@brickerbrickeronenine
please take a look at this and let me know what you think
https://atoddj.github.com/squirtle

**Comment by BrickerBrickerOneNine** [comment]
404

**Comment by BrickerBrickerOneNine** [comment]
changed .com to .io, works. I like the powered  by, but not the placement. lets try far right

**Comment by BrickerBrickerOneNine** [comment]
Or maybe it should be centered, with a title of "Tier 1 Troubleshooter - Powered by Monarch"? until I can come up with a name for this system

**Comment by atoddj** [comment]
@BrickerBrickerOneNine check it out now
https://atoddj.github.io/squirtle/#/
let me know what you think. I believe ultimately we will have to have some designers help us make it look nice (unless we buy a theme)

**Comment by BrickerBrickerOneNine** [comment]
Not quite. So instead of it saying "Monarch" it should say "Tier 1 Troubleshooter" in black, then "Powered by" in grey off centered to the right in grey, and then the Monarch logo

**Comment by atoddj** [comment]
Take a look at it now. If you like it let me know and it can be closed and moved to done :)

**Comment by BrickerBrickerOneNine** [comment]
not quite, the powered is directly to the right and the "to" is really far left on bottom. looks really weird. but of course its rendering different on different browsers.

So I look on Chrome and it looks correct almost, but still directly next. I'd like it to sit to the left, sort of under "Shooter" and the By would be just offset to the bottom right

**Comment by atoddj** [comment]
need a screenshot. i dont see any "to"

**Comment by BrickerBrickerOneNine** [comment]
Works
